baseURL = '/'
relativeURLs = true
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'terminal'

[taxonomies]
  tag = 'tags'

[permalinks]
  [permalinks.page]
    crafts = '/crafts/:slug'
    howtos = '/howtos/:slug'
  [permalinks.section]
    crafts = '/crafts/'
    howtos = '/howtos/'

[params]
  showMenuItems = 0
  centerTheme = false

[languages]
  [languages.en]
    [languages.en.params]
      readMore = "...Read More..."

# [[menu.main]]
  # name = "Blog"
  # url = "/blog/"
  # weight = 10
